### ISSUE TITLE
Maplestory 2 - Engine source

### ISSUE THREAD

**Issue by RUSshy** [Miyuyami/MS2Lib#1]
Hi

This might interest you:

https://github.com/changxy2/BraveProduct

https://github.com/changxy2/NewBraveDemo

Looks like it is the source of the maplestory2 engine

It contains same config file, same file extentions, same directory structures, same .flat file etc

**Comment by RUSshy** [comment]
This is used for motions:

https://emote.mtwo.co.jp/manual/motion/

Folder:
Data/Resource/Library

**Comment by Miyuyami** [comment]
Thank you for being interested in this project. :)

From what I know, MapleStory 2 uses Gamebryo as a game engine.
Those 2 repositories look like a game that someone is trying to make using the same engine.

About the motions, how did you get to that assumption and how do you think that will help this project?
